name = "vas3k-quest-25"
main = "src/index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

[build.upload]
format = "service-worker" 

[assets]
directory = "./public"
binding = "ASSETS"